apiVersion: ENC[AES256_GCM,data:+7I=,iv:J1wiT96YuOCLhvia2Ar4LgoROu+BtOdIIuRLC8I1Kmg=,tag:yzaQa/PQzazYdoPANGwaLg==,type:str]
kind: ENC[AES256_GCM,data:7r5GT4rK,iv:3ZNDQRoDGTUMGfGITjA0ql5fBfsgFjmR6oBqaJdhko8=,tag:hyIBvJCpU5+uZlhlNZk98A==,type:str]
metadata:
    name: ENC[AES256_GCM,data:skVZODRNKyS9pw==,iv:X3iX9zkpYe2punwL6M+Ub57dJ27uANyREf4e5fHUiew=,tag:sgAUm1pXcE7/d0RlUejK3A==,type:str]
    labels:
        app: ENC[AES256_GCM,data:JLfPuYsknWGx,iv:CCRDS7F5ce4FVZCyuWdA1xDSol3JVeGxGgabpWDY3Vs=,tag:qFoFm/pbibXGJZNSisLpvA==,type:str]
        tier: ENC[AES256_GCM,data:3KZ73Po=,iv:EkIwmUiTzJSKDweikDTriMtWt0GEBbmT9txvh0Vf/qI=,tag:56nMrMoqXST3YWzoD1/eCA==,type:str]
type: ENC[AES256_GCM,data:P+bmixGn,iv:JZRYR/xfx/36DdcqCs+YZvU4XF5S/jsNUIfaNZFv0KA=,tag:silAFC7qNNzCR3rBdip/Bw==,type:str]
data:
    password: ENC[AES256_GCM,data:6AjJ6q7bUdW+/+Vq2m3/SA==,iv:4n7N8RDy3diDW9tnOKNnLwaHHCgC10GHpdcRz3GIDN0=,tag:UYVrixpqT1dFP0wtTjgimw==,type:str]
sops:
    lastmodified: "2025-11-17T23:36:40Z"
    mac: ENC[AES256_GCM,data:f2r5MFc0SfdlBKIIXzPl+c3zUaJrBdkD3f4fmRPo8Qly6mwzvhzHi2UrjlJmV5bo2R1KoZ9Gr4UJ8Qeco62W6jwvRIIQNseOLl1IaPQ3Z3zHcIu2Rv3GaHOsMBRTAhEMGck+JVsftW/ZgvSKaa5eQ4L99Gr7xCGp/SSFQLj0Ddc=,iv:SFXDbzYqPS+EJKzzL0AdJmPpqY6cY/h1dy474UHGIxM=,tag:25rAqI4qULh+qLnjKR24JA==,type:str]
    pgp:
        - created_at: "2025-11-17T23:36:40Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA7x6n8gdNICLARAAud67F0Bf3E6LVrFIXHPjU/4fv2fcweSdN6oDI3DjEBSF
            tlyLxZ+Nm1ZosylanYb3r0Bzju+JhDQSacZf7Hk1da9Tvb5TNPTHz2xHJ3ar3jYS
            ZgV4mZva2yCivrpBVTWXu6RyaR1XRVoU3NJ8/ysMkaKVoXG2aV6YR6TbdgQL4+M9
            RaHczcpf9+fxcAMT6zSdtzFo4GcWkd4jgmmaeO8Ytvl2JSvzTDPtaZU31Yhl9Pfh
            9YAJhQeG7Z7pG78+TqfSElGWlnDoYZM2CENEnUH/dsFbAv8I+rEwq4ET3sFstr6Y
            QkUXLB3O6IXGdekPvfpxib1ltLjJBb/nY3CBMfCmTMo8qZaUVvIfuuavORHepOeQ
            ppRr2AroGUurCldhBaIM4gvlP+oAzUBv3bLlPGvTcxeKnBOqNS+UGvzb/TufiSWu
            n77zYxtw2j9V4XemaerWnFfNo5eszR7TP4xc7jsNH1wCH3x34Ng1UMyHy/iFoO6I
            rX77ZkW80wmfnX5KPxwjbv8BOxZbvWky/My8BioOC77tXbzrotojSqpUfysqqhz0
            oSiWSwYl0enjBalAao/JwYBBQ21AbnI8owhAGs0FX6F4/RaM3J1quU1W4rtZyUnM
            k8dDkuxXiecbFZQxLX/G5/uUYRZ3TCZLgdgxtANaTpyNmVL8fHtvJ50zMOd9aKzU
            ZgEJAhBQkLrsrxJnb1Cv+woRJpt4aHIcpLyYCBqX6jB1EMmxtQWUiuOxg0/YTw9N
            JcM3//IG4RMJDueNC/4vytE+Rx21DbQ+4+NTRdnom9RSSSH/XCEV55S936DhPG5O
            SOp1KmwLGA==
            =XDAO
            -----END PGP MESSAGE-----
          fp: 76F6501C6D56ECE1D90BD1050CE3B2921E2242AF
    unencrypted_suffix: _unencrypted
    version: 3.10.2
