---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: redis-secret
  namespace: prod-database
spec:
  encryptedData:
    password: AgB6wNdHi/9PISU/nu6ns3YKbLFLOgqhcfpMJNRPdQ1lekMcwex9hF4zgwfCATP9cHTq1Xbt9ShDNv6hbVEXSakAJ4C++geZw78UJDmkymuxKL1Hwsu0J1JhCxpIGZ46S4wyUfU10CfrmhZr43nnu6Z43gNb/QqU+gB/QFIBvLcZ/gw6LYLOG9Iq4Z3ieMnhCucT9JL29qfSY4H89SZahkTD70MDYKLQVMpRoHmsBkak8MdXDwiClv2JeutHdk5IZS7cVeZHu2lHlxHeVEnEomMTeNgHRY0onYyy/Asvar8AlcTODKUMMn7aYJxSI47HjOy865RI/rO+dY4lnWbCtWfEGENhgrtnyWXPr/92KOvpzDFmflUv43zgiio5JzpU0vJ+Sv3AttzRwILDwj5oL1EyMeLfCVOlibKecf7jHo6WMg0k+V1Bqpd1cCVFZgrBMTUxpDyRDsssstOqdQBEmeVL8Smi4SnE3B03VHfZSWMrXno+q2BLICXZu6df6zlg/gZWy3DRpxU6nd9R+V2qwIFmCGLOEKs7N86SzxV/8tcwboipqUL1nlvFMlt3vgNBi7GAVmbcHQN66ZrI+QdvN8YXqHL8EGN7tRHxyi1OTz1Yr0/JIJBjgFIbr6rLHTjXzDttkUTbAJBLVvlb66xscYI3+pSYVQqZy9Qnj+shr3tdutpKteaF5hkpmPFN1MIST6WzfD2rFMEBrgA=
  template:
    metadata:
      name: redis-secret
      namespace: prod-database
    type: Opaque
