apiVersion: batch/v1
kind: CronJob
metadata: 
  name: postresql-backup
  namespace: prod-database
spec: 
  schedule: "0 2 * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        metadata:
          name: postgresql-backup
          labels:
            app: postgresql-backup
        spec:
          restartPolicy: OnFailure
          containers:
          - name: backup
            image: postgres:18
            command: [ "/bin/sh", "-c", "pg_dump -h postgres-service -U postgres -d portfolio_db -f /backup/backup_$(date +%Y%m%d_%H%M%S).sql" ]
            env:
              - name: PGPASSWORD
                valueFrom:
                  secretKeyRef:
                    name: postgres-secret
                    key: password
            volumeMounts:
            - name: backup-storage
              mountPath: /backup
          volumes:
          - name: backup-storage
            persistentVolumeClaim:
              claimName: database-pvc
        


