apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: database-pvc
  namespace: prod-database
spec: 
  storageClassName: "nfs-client"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi