apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: secure-db-access
  namespace: prod-data
spec:
  podSelector:
    matchLabels:
      app: db
  policyTypes:
  - Ingress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          team: admins
      podSelector:
        matchLabels:
          role: maintenance
    - podSelector:
        matchLabels:
          app: web
    ports:
    - protocol: TCP
      port: 5432