apiVersion: ENC[AES256_GCM,data:bxM=,iv:B6FxGefb6PWH9KsHgGD9EjoB3X8HQTEXXCPyZqQgrFM=,tag:si0b3fj6gOmu61yQxGaLgQ==,type:str]
kind: ENC[AES256_GCM,data:yVjSuMDk,iv:fCewLfeRw/Ss146kApYHYZEnfj0m/lFsM8/EWuPI1d8=,tag:7Zhj/rXkHgugQkpCH3bycg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:hhaLXl5a7RTrAzz5xlPoiUu4S7U=,iv:MebaGXzxIUfZiTPTEUPuS7wAxB2vk/mYgZ6us9sSnp4=,tag:O4bI1l4mJEYcVv064RRa2g==,type:str]
    namespace: ENC[AES256_GCM,data:R5i/cARKnzAf0ZE=,iv:4Ce/8pFq9Xi6i0e9Rcf9pcrxfz9LG3qEqkeuEjbSyZY=,tag:r6MnUVHn0cm17PzlQ5mFUw==,type:str]
type: ENC[AES256_GCM,data:gr2o8Prx,iv:WqhFID882luCaaVnGAkVN4ZGfZWG5eSfUVFyoNYsJnM=,tag:41NZ5jqgMo85Tk9tg4lWiQ==,type:str]
data:
    azurestorageaccountname: ENC[AES256_GCM,data:i7jrLBZNpLo=,iv:uG2yZ3jo38lj7FPe5RI4ImhIK4hL55V0RFA8pX5OFSg=,tag:ToMvAMb0yoyhwmbwWXRSAg==,type:str]
    azurestorageaccountkey: ENC[AES256_GCM,data:l9pkp6bHVY31P2F7dhjmPy3ey6SzHe0pI5mOH62MOTH7T6cEzCpK20szxiWpYQSrYvd4TH63PlPsjl6OdG1xVj4ziDKQJ2GeN+WuGKecNmxO5pSn2g7JlsPadmTr4RTCXifyBq0l1bFFNVUoJPonqwJS8bbt1HPd,iv:LM9olCQzzjASETsLR4jsR1CJMprFiqWG5YcRFIYpK4s=,tag:JMejM1dIj9Ph+skK093nGQ==,type:str]
sops:
    lastmodified: "2025-11-17T21:53:23Z"
    mac: ENC[AES256_GCM,data:GbGbucxPvclSHDp8DI417sqxBTd4ZURDdO3d1hWoM4/O8gd7z30UQ3sfu3lX1tMVHfvjqN/6SMISJup+WixiT3BsZD4XkwufPFc0qDf+46R6Wv52kOgFjmqPHUlgVzQxKv9rMiWwU/u/kTKCQ0HksOYge16BQC8Z5HHf+HUzw/A=,iv:B05pe6NP6k6+cnvmEYdZNnGJeGqpj8iEchblCObNjEM=,tag:2ENDT+HQc+QLXCUKQhk8og==,type:str]
    pgp:
        - created_at: "2025-11-17T21:53:23Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA7x6n8gdNICLAQ/6Aq5cy4DGliOvOMZ0IJeKvCcrTWX//9bnWAiOGLqk37GW
            qSRAp+J4gJKbLvreNDkXDYTVASWjXFZ5w7QM5Jh4lQ2fhLL+WOHjljGG2ye/X3B4
            wCgmM/m6C9EO+lOeT5jgt2Tc8tDl49bcM6kfdewF3tH7bfbxeCh9LXuw98dOw2DY
            Izx4Lxdc58qwP/Pw5yHwfE4XGl4uJeKy21hD4QR8b3NfgRdZxdIxr7npK2gAeiZ/
            xbUFZH+zCUDHa5EpPKcTg3TgpcW1S7ru8gZSC/AfnHGVQbaZWbMN72nTtcBv98nJ
            bFvINjixGErE+4no3oH3kD20wotbV/yX+YgVg8O35BAWy3/WJACRsxdwIVmb7scn
            kwhMRxbKhqetdOeS/1Y6AdP6FZ3d2uqyhf540vU1j8bDToAcaIuyUK7GeA4YQ0mv
            knRwhWIp/YMGB8TUCN1agRWaRSOub+YNarf7XPVOUptZMx+BFjZFhoZnHwTWJb5q
            0zj+CoeyopFTADv5ArO1gXJIfGJgvWr4gIDWsBWbCZghLYpxjMaigm/vfRdSjH9S
            CoDs7NMxCkEGQh1HVwXay1n8lX4SF7IqF4g4xANfCAh6m0HA5T2bZsn/Hxb8Tb80
            G3Yikqi/khzYLauTQuPKZ0THwubARF6F3nmWRM9JeFoy4reegOup8kHMtCsph/zU
            aAEJAhDh413FZT/fbIAXwoD/unHccNnIIJxmCN/H7a9EPqsZv3Q9DSSQ4B8OmSEG
            4KfcL4GZz67nvkurywPOsYijvT44pA8okat1Cyhqnx7nu8FVVuy2Dkpxb8svlwyX
            noXQcwx9393k
            =xjr8
            -----END PGP MESSAGE-----
          fp: 76F6501C6D56ECE1D90BD1050CE3B2921E2242AF
    unencrypted_suffix: _unencrypted
    version: 3.10.2
