---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-secret
  namespace: prod-database
spec:
  encryptedData:
    password: AgAtQWrQqcxHrAeT/UINadbcx3FBQqqhL2mA3LI42rEoHTFNsMkNNKSVdwxyypVHlUWxm9bD8TwXdsb8k+mA0U7ytoBFpbvr9d3u5pOoCsVFQGwuVTR3n5UAbNuxoW2aLatxOxZYWbdIJjQWtbYnAg6SD9bEa79pnsA8xSgR5xecOnM+caxfHTvd7sEutiqq2BSqZKpP+uG/V7HmoTOHwl/9dAPYLf6SnVKPH9Ys60SODP5Mho7Db2Kt80coMRWHlODNQ6WsSNnuCYonW9mlu+culwCFf57AiLqlbiEa6+7Fo7+qNjsmr8b+Sn9ZTYOUHR+x2Ij0GxolQJJmWWdTfngcMuIQE7qbbYmk/k1WnPpjitRwMtWPmKVj6PZwJaSDFDSHIzYvJ2xB7wIs6DKj+HRxXtlKHSwqb0vwfexpTMS77pZCXBFWlJ7x/dMF0GxNUMOQcA1eFwlTQgm65Xvww1rEqKCFEoR/UglnFSxYP5R63G9mUoN6/yCt7EX+sLcdJ/mk9wM3eeM/nRwns24KteEz0okK4bLLP55fKk1WWfCKcZexxW0E37Vv6YQTie9rZZ5iVyS3Vn6B9wDAgLnEeGAjgt4B87E0PiQmHLdYjCt/5xta+/c+VJG9jM9P1rzEpIgMa8xzVK/OjY1sQAfhEtGSanoJEs3yMiiv7ldHMSE8C+GmuvfB6yw1gJDdOCSz04KX60W+BS5tbRf+rQ==
  template:
    metadata:
      name: postgres-secret
      namespace: prod-database
    type: Opaque
