apiVersion: v1
kind: Service
metadata:
  name: portfolio-frontend-service
  namespace: prod-database
spec:
  selector:
    app: portfolio-frontend
    tier: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
