apiVersion: batch/v1
kind: CronJob
metadata:
  name: CronJob
spec: 
  schedule: "*/5 * * * *"
  jobTemplate: 
    spec: 
      containers: 
      - name: cronjob 
        image: busybox
        command: ["sh", "-c", "echo 'Tache executee a $(date)'"]
      restartPolicy: Never 