apiVersion: batch/v1
kind: Job
metadata:
  name: job-indexed
spec:
  completions: 3
  parallelism: 3
  completionMode: Indexed
  template:
    spec:
      containers:
      - name: job
        image: busybox
        command: ["sh", "-c", "echo Traitement de l'index $(JOB_COMPLETION_INDEX)"]
      restartPolicy: Never