apiVersion: v1
kind: Service
metadata:
  name: portfolio-backend-service
  namespace: prod-database
spec:
  selector:
    app: portfolio-backend
    tier: backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: ClusterIP