---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-secret
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgCW8pBUsduYM7KP3PWBF4/zPojJQ9yGfBIpooSLwWbYgMPTfwLAeMG6FkKqjx5al/H5YgjEKTO49+wJeknphgyoI4QJSvYfYjJd/rhHww34XQIAf1/gB5xxjmCcK9678QBNTz00zUxMaix4l9une7trjLFY40vtamqIsmJOjmPEC5NakoG1WCwbyBAEFk+wYyzeaVs65cX3X4Zvtd8YSsPqSr4zZlDLLgQ9BMEdtMcKYcp6wqVa8j082oIj+YHHtNxd3pUCojLPmVrVeM4gYcathh9biRMBRueLMmJZ36uEw8gDYIDyVDSp4B3J5WI8t9m6XO+pD6t0ZXMEriMnLM54KD13qVlvtBk3SABTNaqD5GW2/3EPyInzXaf/eSmNhZknMPcCDarfZRd3Cmr5t3XezramIC+xkyuFytxdWS1qmez+HEwukRdOZnr/hOhYNXNOkRXHgZRY/B3EjQ4La8kc/SBBA8TycGq2HH7DSA0cGVJINWVz/xN9VlTT0j5ms3dvDfi77lGUWfu5biEB/wDwGD6gYmNPC3FNYq9pM4W6hSe49hKctp/WecLRnI2Re4pXDhZIMV7lW/LLkbMpxkfCWxxiv/MOlncwDUTPaH4kHECDwdm6iNZS1mAtzhSK/7ABNtoNZdRtQKA+x2w4r57czRFJwN06E+wdCDdtyYDI+7B6kdP0sU3s4BR8nsHALfm9qjzRNU36o5CR6Q==
    admin-user: AgBwkhnry5FXKhen/4drVcS1hIg6jkQLCnx2s56vQGyd30uoOBsBk7UhyhXPTDimYSrrUsSXqtzHUGsBB6CJ5ZPsPfI2Cxn9GqEQnHniOl7ArzjPnwsLLoFrpfNnU4cmnmz+GmOFe3ARXyngQM7HxpPZ4QJbnQj+HHYUUXBUJkH76DkHo4ecQf3NOw/fzLaCT5iDfPUJp20NW9gqgU0pFbquXUQIgi4ULgo4wD6jIKD/fxm25H6qkIyZXpEMJogRrKM0DorVCurUorkC7svx+M6ZIAcGFLmq8XG6DVzxfhaaePVk3UD5OtKkAWB9LzZ6cLhd2FLPNn88bF2PbqGn6wo/nuTgEM2aFQx3rIm9zOjPT8ncyo+W6MMxpTST35smmV/tw0d/uKSIOv8DTOegFUwtANyE+pU26w2bAS9hXmwk9o/GGy5DcOH5ptKEMApNjS5ds7aUBT6+qC/KTBAiJeAUlFnbHwMBpy2fZsUkSTGiP7vRIz/v+3RT9BNILvnqGvZDEfbfIoUY6GPN4YiUloGY4hvfxcm6Kz2pCT8w5e/StPd/pr9Zj2zFY+Ewb43llWq9zNFbRSSRhMUkGHoqFr3Ss+OuFkOjbuD/edSI2BDpTEoCyb0MsfGrMcoSpLHwsDVy0ftjiROPsaB9B5RUUsXQfwKjMWRppssWDYeV+2ulSAekyJyxFQNvD7WBErSLwiE8kUQ2LT3nXZIQOqNi
  template:
    metadata:
      name: grafana-secret
      namespace: monitoring
