server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html;

    # Gérer le Routing React (SPA) : renvoyer index.html pour toute route non trouvée
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Pas de bloc /api/ ici ! 
    # C'est l'Ingress Controller qui interceptera /api/ AVANT d'arriver ici.
}
