apiVersion: v1
kind: Service
metadata: 
  name: svc-pay
  namespace: prod-app-shop
spec:
  selector:
    app: app-shop
    tier: backend
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 80