apiVersion: apps/v1
kind: Deployment
metadata:
  name: secret-volume
  labels: 
    app: secret-app
spec: 
  replicas: 1
  selector:
    matchLabels:
      app: secret-app
  template:
    metadata:
      labels:
        app: secret-app
    spec:
      containers: 
        - name: test-secrets
          image: nginx
          volumeMounts:
            - name: secret-volume
              mountPath: /etc/config
      volumes:
        - name: secret-volume
          secretName: 
            name: yml-secret


